### ISSUE TITLE
Create a "test"/sandbox stall

### ISSUE THREAD

**Issue by matiasilva** [SRCF/lightbluetent#15]
This will allow stall managers to play around with their set up before the big day.

**Comment by edwinbalani** [comment]
I'm wondering if it might be more natural for stallholders to set up their own stall in a "draft" or "private" mode, so that everything can be how it should be before "opening" their stall?

I imagine most people could muster up a few friends or committee members (or spare devices) to test out the stall in such a way.

**Comment by matiasilva** [comment]
This is a good point. I had floated around the idea of doing a "preview" but this works better.

**Comment by dnlburgess** [comment]
Is it necessary to have a 'private' mode while testing? How could we tell BBB which users can / cannot join the stall when it is in this mode?

**Comment by matiasilva** [comment]
I don't think this would be useful for anyone after thinking about it. We can consider a "test" mode, ie. the admin can publish the page or keep it in test mode. But again what additional functionality could this have?

**Comment by matiasilva** [comment]
I don't think this is a feature we'll be considering for now.
